/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type FeatureCard = {
  _type: "featureCard";
  title?: string;
  bullets?: Array<{
    text?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "bullet";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ClientItem = {
  _type: "clientItem";
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  quote?: string;
  tagline?: string;
};

export type ProcessStep = {
  _type: "processStep";
  number?: string;
  title?: string;
  description?: string;
  descriptionHighlight?: string;
};

export type ServiceItem = {
  _type: "serviceItem";
  number?: string;
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  linkLabel?: string;
  link?: string;
};

export type Separator = {
  _type: "separator";
  width?: "full" | "half";
};

export type TextBlock = {
  _type: "textBlock";
  number?: string;
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type BrandLogoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brandLogo";
};

export type LogoWallSection = {
  _type: "logoWallSection";
  title?: string;
  logos?: Array<
    {
      _key: string;
    } & BrandLogoReference
  >;
};

export type RichTextSection = {
  _type: "richTextSection";
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type FeatureCardsSection = {
  _type: "featureCardsSection";
  heading?: string;
  cards?: Array<
    {
      _key: string;
    } & FeatureCard
  >;
};

export type InfoBoxSection = {
  _type: "infoBoxSection";
  headline?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  boxTitle?: string;
  boxDescription?: string;
};

export type ImageSection = {
  _type: "imageSection";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type ClientsSection = {
  _type: "clientsSection";
  label?: string;
  supportLabel?: string;
  showViewAllLink?: boolean;
  viewAllLabel?: string;
  viewAllSlug?: string;
  clients?: Array<
    | ({
        _key: string;
      } & ClientItem)
    | ({
        _key: string;
      } & ProjectReference)
  >;
};

export type FilmReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "film";
};

export type FilmShowcaseSection = {
  _type: "filmShowcaseSection";
  label?: string;
  heading?: string;
  introText?: string;
  films?: Array<
    {
      _key: string;
    } & FilmReference
  >;
};

export type TeamMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teamMember";
};

export type TeamSection = {
  _type: "teamSection";
  heading?: string;
  teamMembers?: Array<
    {
      _key: string;
    } & TeamMemberReference
  >;
  outroText?: string;
  outroHighlight?: string;
  ctaLabel?: string;
  ctaLink?: string;
};

export type TwoColumnSection = {
  _type: "twoColumnSection";
  label?: string;
  leftHeading?: string;
  leftHeadingItalic?: string;
  rightBodyText?: string;
};

export type ProcessSection = {
  _type: "processSection";
  label?: string;
  steps?: Array<
    {
      _key: string;
    } & ProcessStep
  >;
};

export type QuoteSection = {
  _type: "quoteSection";
  largeHeadline?: string;
  largeHeadlineItalic?: string;
  quoteBoldText?: string;
  quoteRegularText?: string;
};

export type CtaSection = {
  _type: "ctaSection";
  headline?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  buttonLabel?: string;
  buttonLink?: string;
};

export type ReferenceWorksSection = {
  _type: "referenceWorksSection";
  heading?: string;
  allLabel?: string;
};

export type FeaturedWorksSection = {
  _type: "featuredWorksSection";
  heading?: string;
  showViewAllLink?: boolean;
  viewAllLabel?: string;
  viewAllSlug?: string;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type ServicesListSection = {
  _type: "servicesListSection";
  label?: string;
  leftHeading?: string;
  leftHeadingItalic?: string;
  items?: Array<
    {
      _key: string;
    } & ServiceItem
  >;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type HeroSection = {
  _type: "heroSection";
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  backgroundImageMobile?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  backgroundVideo?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  backgroundVideoMobile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  headline?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  subtitle?: string;
  showScrollIndicator?: boolean;
  showSocialIcons?: boolean;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type BrandLogo = {
  _id: string;
  _type: "brandLogo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headingLine1?: string;
  headingLine2?: string;
  headingHighlight?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  email?: string;
  phone?: string;
  copyrightText?: string;
  legalText?: string;
};

export type Film = {
  _id: string;
  _type: "film";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
  director?: string;
  production?: string;
  coproducer?: string;
  partners?: string;
  status?:
    | "in-development"
    | "in-production"
    | "in-post-production"
    | "finishing"
    | "released";
  publishedAt?: string;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  email?: string;
  phone?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  order?: number;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  client?: string;
  slug?: Slug;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  category?: "film" | "branding" | "marketing" | "produkce";
  excerpt?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  publishedAt?: string;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  logoText?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  socialLinks?: {
    instagram?: string;
    linkedin?: string;
    facebook?: string;
    vimeo?: string;
  };
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedAt?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  isHomepage?: boolean;
  blocks?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & ServicesListSection)
    | ({
        _key: string;
      } & FeaturedWorksSection)
    | ({
        _key: string;
      } & ReferenceWorksSection)
    | ({
        _key: string;
      } & CtaSection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & ProcessSection)
    | ({
        _key: string;
      } & TwoColumnSection)
    | ({
        _key: string;
      } & TeamSection)
    | ({
        _key: string;
      } & FilmShowcaseSection)
    | ({
        _key: string;
      } & ClientsSection)
    | ({
        _key: string;
      } & ImageSection)
    | ({
        _key: string;
      } & InfoBoxSection)
    | ({
        _key: string;
      } & FeatureCardsSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & LogoWallSection)
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & Separator)
  >;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | FeatureCard
  | SanityImageAssetReference
  | ClientItem
  | ProcessStep
  | ServiceItem
  | Separator
  | TextBlock
  | BrandLogoReference
  | LogoWallSection
  | RichTextSection
  | FeatureCardsSection
  | InfoBoxSection
  | ImageSection
  | ProjectReference
  | ClientsSection
  | FilmReference
  | FilmShowcaseSection
  | TeamMemberReference
  | TeamSection
  | TwoColumnSection
  | ProcessSection
  | QuoteSection
  | CtaSection
  | ReferenceWorksSection
  | FeaturedWorksSection
  | ServicesListSection
  | SanityFileAssetReference
  | HeroSection
  | Category
  | Slug
  | BrandLogo
  | SanityImageCrop
  | SanityImageHotspot
  | Footer
  | Film
  | TeamMember
  | CategoryReference
  | Project
  | Settings
  | Post
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
